spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/journi_prim_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379

security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=86400000

journi.seed.roadmaps.enabled=false
journi.seed.roadmaps.dataset-location=classpath:seed-data/backend-java-spring-roadmap.json
journi.seed.roadmaps.exit-after-run=false
